app:
  back-url: localhost:8081/art-tracker-back
server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /art-tracker
spring:
  mustache:
    charset: UTF-8
